src/tests/intergration/ManageZonePage.test.js
Due to changes with the `PrimaryButton` component, a selector for a button in the `ManageZonePage` test was not working as expected. I've fixed it, and hopefully made it a little less brittle.
=> Fix failing test

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js, src/components/rangeUsePlanPage/schema.js
The elevation dropdown component was using the `elevation` value sent from the server, when it instead should have been using `elevationId`. `elevation` is a populated object, but the dropdown expected just the id, which caused an error to be thrown.
Relates to #126.
=> Fix plant community elevation dropdown error

src/components/rangeUsePlanPage/schema.js
Allows an empty value to be provided for allowable AUM, and gives a better error message for invalid inputs.
Fixes #134, fixes #135
=> Fix allowable AUM validation

src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.story.js, src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/StubbleHeightBox.js
Populates the value field for range readiness and stubble height indicator plants, based on the value provided `PLANT_SPECIES` reference. If the default value isn't specified for a given plant, the value (either leaf stage or stubble height) won't be updated.
Related to #143, #144
(Should probably wait to merge this until we have zenhub configured)
=> Populate default value for indicator plants

src/components/common/form/DayMonthPicker.js, src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js, src/components/rangeUsePlanPage/schema.js
Uses the `DayMonthPicker` component to set `rangeReadinessMonth` and `rangeReadinessDay` in the form instead of `rangeReadinessDate`, which doesn't set anything in the db.
Relates to #137, #167
=> Send range readiness date as separate month and day

src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.story.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/ShrubUseBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/StubbleHeightBox.js, src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js, src/components/rangeUsePlanPage/schema.js, src/styles/Common.scss
Marks required fields in plant communities and sub-sections as such.
Also fixes the saving of plant community actions and indicator plants, which wasn't implemented.
Relates to #165, #231
=> Mark fields as required in plant communities

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.story.js, src/components/rangeUsePlanPage/schema.js, src/styles/RupPlantCommunity.scss
Also fixes up the layout a bit.
Relates to #169
=> Allow setting of plant community action name when type is 'other'

src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.story.js, src/components/rangeUsePlanPage/schema.js
Shows another field when the indicator plant type is "Other", which allows a user-provided value to be persisted.
Relates to #177.
=> Allow name to be set when indicator plant type is other

src/components/common/form/ErrorMessage.js, src/components/common/form/InputRef.js, src/components/common/form/PercentField.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/pastures/PastureBox.js, src/components/rangeUsePlanPage/schema.js
The textfield presented to the user still expects percentage formatted numbers, not decimals. This is just to align with the behaviour of the iOS app, to ensure it remains consistent.
Relates to #221
=> Store PLD percentage as decimal

package-lock.json, package.json, src/components/common/form/DayMonthPicker.js
Customizing the DateInput from semantic-ui-calendar-react wasn't enough for our-use case, so I've created a DayMonthPicker from scratch which allows a user to pick just a month and day, without a year.
Relates to #137, #166 and #248
=> Create custom month and day picker

src/components/common/form/DecimalField.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.story.js
Uses a new DecimalField component to ensure that indicator plant values always display to one decimal place. Also filters out shrubs from the indicator plant type dropdown.
Relates to #178, #239, #176
=> Set indicator plants value to 1 decimal place

src/components/common/form/PercentField.js
Allows fields such as pldPercent to have only whole number percentages.
Relates to #221
=> Add prop to disable decimals in PercentField

src/components/common/form/DayMonthPicker.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.story.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/ShrubUseBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/StubbleHeightBox.js
Allows an "other" value to be provided right in the dropdown for indicator plants and plant community actions. Also adds a search feature.
Relates to #169 and #177
=> Better "other" selection for dropdowns

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
Because of component memoization the grazing schedule wasn't updating it's calculations when fields in other sections were changes, like the value for PLD percent. I've unmemoized the component for now to resolve this.
=> Don't memoize GrazingScheduleEntryRow

src/api/index.js, src/components/rangeUsePlanPage/index.js
Before, all the saving logic for the data in plans was directly in the `onSubmit` handler of the form. I've broken them out into a separate file, cleaning up the submit handler. 
Resolves #212
=> Break out plan API calls into separate file

src/components/rangeUsePlanPage/DownloadPDFBtn.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/components/rangeUsePlanPage/pdf/PDFView.js, src/components/rangeUsePlanPage/pdf/pdf/index.js, src/constants/routes.js, src/utils/hooks/pdf.js
iOS doesn't support the inline PDF viewer used previously, so the implementation has been changed to simply render a link to the blob directly. This should have more cross-browser support. Also moved the PDF download to a modal rather than a separate page.
=> Have PDF downloaded through URL, rather than displaying inline viewer

src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js
Calls the API endpoint to update the user confirmation when an agreement holder submits the plan. This is to match the existing behaviour when there are multiple agreement holders.
=> Update confirmation when single agreement holder submits RUP

src/components/router/ProtectedRoute.js, src/components/router/PublicRoute.js, src/components/router/index.js
There is inconsistent behaviour between loading the user data by connecting to the redux store and by using the `useUser` hook. Since underlying components are using the `useUser` hook they were getting an `undefined` user before the parent component was trapping the change and redirecting the user to the login. 
Resolves #295
=> use useUser hook in Router component

src/components/rangeUsePlanPage/BackBtn.js
The "back" button beside the RAN number should redirect the user to the RUP list page, not act as a browser back button. 
Addresses issue #296
=> redirect to list page from range use plan

src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js, src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js
Allows agreement holders to edit the minister issue action type after it has been created. Also lets them delete actions that have not been persisted yet.
Relates to #297 and #298
=> Allow minister issue actions to be deleted and edited

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
Fixes a bug where the "Add Row" button wouldn't work because it was attempting to pull the value for `graceDays` from the pasture, but there was no selected pasture yet.
=> Handle if no pasture is set in grazing schedule entry row

src/api/index.js, src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js, src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js
Didn't realize that there was already a delete endpoint for minister issue actions.
Relates to #307
=> Let persisted minister issue actions be deleted

src/api/index.js, src/components/rangeUsePlanPage/PlanForm.js, src/components/rangeUsePlanPage/managementConsiderations/ManagementConsiderationRow.js, src/components/rangeUsePlanPage/managementConsiderations/index.js
@calebissharp, I'm sorry that this has your changes from #311. I was having trouble saving the form to test out the behaviour I was trying to add. Unfortunately, it didn't solve my issue. I eventually just resorted to using my own backend instance so I could create a clean environment. However, in that version the `ID`s are numeric, not UUIDs. Can you confirm that the `ID`s will indeed be UUIDs in prod?
I noticed in your implementation of the Minister Issue Actions (#305) you added a delete function to the `api/index.js` instead of using the `actionCreators` function that already exists. Is the goal to eventually move all the api calls to the `api/index.js`?
Resolves the issue #299 .
=> Allow Management Considerations to be deleted

src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js
There was an extra `grazingSchedulesMap` argument being provided to the `handleRupValidation` function, which was causing errors. I've removed it from every place it is called.
Related to #309 and #310
=> Remove extra argument to validation function called on submit

src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js
The confirmation endpoint seems to update the status of the plan to `14` automatically. This isn't the status we want when submitting for feedback, so I've added a check to only update confirmations when submitted for final decision.
=> Don't update confirmation if submitted for feedback

src/components/common/form/DayMonthPicker.js
This is to address the issue https://github.com/bcgov/range-web/issues/168
When a date is chosen the calendar closes.
=> setOpen to false on date click in DayMonthPicker

src/utils/helper/plan.js
=> planStartDate is assigned a value but never used

src/api/index.js
There was a missing `await` when creating new pastures, which caused an error when a new pasture and plant community were added.
Relates to #321
=> Wait for pasture creation when saving draft

src/components/rangeUsePlanPage/pastures/PastureBox.js, src/utils/helper/plan.js
Removes an extra status check which was causing the plan to be incorrectly editable for certain statuses
Also hides the pasture menus when not editable.
Relates to #326
=> Fix which statuses are editable

src/components/rangeUsePlanPage/grazingSchedules/index.js
Data wasn't being properly formatted when copying one schedule to another, causing various bugs when saving, and with the date picker.
Relates to #339.
=> Fix grazing schedule copy behaviour

src/utils/validation/grazingSchedule.js
Check if `livestockCount` is a number, rather than just `if (livestockCount)`, which will fail for situations where the value is 0.
Relates to #361
=> Fix grazing schedule entry validation 

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/Import.js
Issues resolved:
* Wasn't correctly importing the range readiness date
* Wouldn't save imported indicator plants properly
* Was showing currently active plant community in dialog
Relates to #173 and #140
=> Fix criteria import

src/components/rangeUsePlanPage/pageForAH/AHSignatureModal.js, src/components/rangeUsePlanPage/pageForAH/index.js
Refetches the plan after an agreement holder successfully adds their signature to make sure the correct information is shown.
Relates to #335
=> Refetch plan when signed

src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/utils/helper/plan.js
> * AH needs "Submit" for all statuses they can edit (see #326 for list).
> * staff need "plan actions" and no submit for all statuses they can edit EXCEPT 6 in which they need the submit button instead
> * for statuses no one can edit there should be neither submit nor plan actions for anyone.
Relates to #374 and #375
=> Adjust when submit button appears based on user role and plan status

package-lock.json, package.json, src/api/index.js, src/components/App.js, src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/DownloadPDFBtn.js, src/components/rangeUsePlanPage/PlanForm.js, src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js, src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js, src/components/rangeUsePlanPage/pageForStaff/UpdateStatusModal.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/components/rangeUsePlanPage/plantCommunities/index.js, src/components/rangeUsePlanPage/schema.js, src/components/rangeUsePlanPage/versionsList/NoVersions.js, src/components/rangeUsePlanPage/versionsList/Version.js, src/components/rangeUsePlanPage/versionsList/VersionToolbar.js, src/components/rangeUsePlanPage/versionsList/VersionsList.js, src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js, src/components/router/index.js, src/constants/api.js, src/constants/routes.js, src/constants/strings.js, src/utils/hooks/plan.js
Changes:
* Adds a new route for viewing of past versions of a plan
* Creates new version of a plan whenever it is saved (we'll probably want to change this, to only change on status update)
* Adds edit functionality to a few more components, thanks to new endpoints introduced in https://github.com/bcgov/range-api/pull/77
I'm not entirely sold on the UI for the version page. Suggestions would be appreciated. I've also moved some of the action buttons at the top into a dropdown, since we were accumulating them and they started to break the layout.
=> Add versioning support

src/utils/calculation/grazingSchedule.js
The total AUM calculation was broken because the pasture was being pulled incorrectly, resulting in the PLD percent always being 0.
Related to #404 and #405
=> Pull PLD from pasture when doing AUM calculation

src/api/index.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/constants/api.js
Previously, deletions were only client-side and didn't reflect any change in the database.
=> Persist plant community action deletes

src/components/rangeUsePlanPage/managementConsiderations/ManagementConsiderationRow.js, src/components/rangeUsePlanPage/managementConsiderations/index.js, src/styles/RupConsiderationAndRequirement.scss
The `Considerations` and `Details` header were fixed to the top of the box and weren't displaying above anything but the first box. They should appear in every box above their inputs and with the same styling as the `URL` header (and the headers in the `Additional Requirements` boxes).
=> Fix ManagementConsiderations header to display in every row and to match AdditionalRequirements

src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js, src/components/rangeUsePlanPage/additionalRequirements/index.js
* Allows the same menu option to be selected more than once in a row.
* Makes delete more optimistic, by closing the modal before waiting for the request to complete.
Relates to #147
=> Fix additional requirement bugs

src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/utils/validation/grazingSchedule.js, src/utils/validation/plan.js
Some validation functions were still expecting a pastures map (leftover from redux). They've been changed to take the pastures array directly.
Relates to #449
=> Change validation functions to use pasture array

Jenkinsfile
Leaving img build despite resources used because it's still the path for prod deployments.
=> disable jenkins test deploy

Jenkinsfile
Not necessary to deploy to test from Jenkins anymore, now that we have GH Actions doing that.
Resolves #462
=> Add back manual approval requirement for test promotion

src/components/rangeUsePlanPage/pastures/index.js, src/utils/helper/pasture.js, src/utils/helper/plantCommunity.js
The copy pasture handler was just a stub. It's now implemented fully.
Relates to #441
=> Fix pasture copy button

src/components/rangeUsePlanPage/pageForStaff/UpdateStatusModal.js
Prevents the update status modal from closing while a plan is being submitted
Relates to #466
=> Show spinner while status is being updated

src/components/rangeUsePlanPage/plantCommunities/criteria/StubbleHeightBox.js
`communityId` wasn't being passed to the `IndicatorPlantsForm` component for stubble height.
Relates to #457
=> Fix stubble height delete

src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js
Updates the confirmation to true when submitted for the user that triggered the submission.
(Potentially) relates to #335
=> Set confirmation to true for multi AH plans on submit

src/components/common/Loading.js, src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/constants/strings.js, src/utils/validation/plan.js, src/utils/validation/plantCommunity.js
Requires that all plant community "verified by minister" toggles are set to true before staff is allowed to submit a plan to agreement holders.
Relates to #378
=> Verify minister approval before allowing submission

.storybook/mocks/plan.js, src/components/common/SortableTableHeaderCell.js, src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js, src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js, src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.test.js, src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap, src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap, src/components/rangeUsePlanPage/grazingSchedules/index.js, src/styles/Common.scss, src/utils/helper/grazingSchedule.js
Allows grazing schedule entries to be sorted, and persists sort configuration.
Relates to #489
=> Add grazing schedule entries sorting

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
Fixes the pasture sort and allows you to click twice on the header to remove the sort.
Relates to #489
=> Tweak schedule sort

src/components/manageClientPage/index.js
Excludes users who log in through IDIR and with the username `myrangebc`.
Relates to #612
=> Change manage client user dropdown filter

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js, src/utils/helper/additionalRequirement.js, src/utils/helper/grazingSchedule.js, src/utils/helper/pasture.js, src/utils/helper/plantCommunity.js
Prevents copied fields from changing order after save, as they were inheriting the `createdAt` value from the field they were copied from.
=> Remove createdAt when fields are copied

src/components/rangeUsePlanPage/grazingSchedules/index.js
=> Clamp array length at 0 to fix plan date picker crash

src/components/rangeUsePlanPage/plantCommunities/index.js
* Fixes which property is used for the name in the delete modal
* Deletes by ID, rather than index, to prevent deletion of the wrong record.
Relates to #619
=> Fix some issues with plant community deletion

.github/workflows/deploy-test.yml
For reasons I can't remember --wait=True was on one of the builds but I don't think that works, plus you don't see errors.
=> use same wait command (-F) for both builds

.github/workflows/deploy-test.yml
Regular wait command doesn't work for builds using another image stream as input.  Now I know.
=> Change wait command back for caddy build in gh action

src/components/common/ListModal.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/components/rangeUsePlanPage/plantCommunities/criteria/Import.js
* Fixes issue where name wouldn't appear when source plant community was unsaved
* Fixes indicator plants being overwritten, even if not part of the selected criteria
* Disables selecting a pasture with no valid plant communities to import from
Relates to #617
=> Fix some bugs with criteria import

openshift/templates/build.json
Build pods were getting killed at 2Gi, rolling with 2500Mi and will work to optimize.
=> update bc to 2500Mi for now to avoid OOMemory errors

src/components/rangeUsePlanPage/BackBtn.js, src/components/rangeUsePlanPage/schema.js
Default page when query parameters couldn't be found was set to 2, causing no agreements to show up when there were only enough results for 1 page.
Relates to #663
=> Fix back button default page

src/components/selectRangeUsePlanPage/SortableAgreementTable.js
Staff contact name was previously being pulled from the first plan for each agreement, causing no contact to appear for agreements without a plan. I've reverted it back to the old behaviour of pulling this name from the agreement instead.
Resolves #674
=> Change source of staff contact name to agreement

src/components/rangeUsePlanPage/DiscardAmendmentButton.js
Was using an nonexistant prop, `onClose`, instead of the proper `onCancel` to handle the modal cancellation.
Relates to #606
=> Fix amendment discard cancel button

src/components/rangeUsePlanPage/basicInformation/index.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js, src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js, src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js, src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js, src/reducers/commonStoreReducer.js, src/utils/helper/plan.js, src/utils/localStorage.js
The `useReferences` hook is being used like it will always return the correct object of populated references, but this is not always the case since the data is initially retrieved from the API. I've added a default value that sets each key to an empty array, and then also added some checks to the components that consume references.
Relates to #689
=> Add more checks for missing references

Caddyfile
Sets the cache header for `service-worker.js` to try and stop the browser from caching it.
=> Set cache header for service worker

src/actionCreators/commonActionCreator.js, src/providers/ReferencesProvider.js
When you first load MyRange without being signed in, a request is made to fetch the references from the API. The request fails because it was unauthorized, but is not retried after the user logs in. This leads to strange errors stemming from the references not being set in local storage. 
The fix I implemented is to refetch references whenever the `user` object changes (ie. on sign in).
Relates to #719, #720, #715, (maybe) #711
=> Fetch references on login

src/api/plan.js
As we'll need to have more statuses than approved getting snapshotted to meet #683 , and we'll have to filter those out anyway for #700 .  This will leave some inaccessible/invisible to user draft snapshots, but I actually want those in there for now for troubleshooting production issues.  We can address storage/retention concerns with a purge rule later.
=> Make snapshots on all saves

src/api/plan.js, src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/pageForStaff/index.js
This PR unhides the amendment button, and gives the ability for staff to initiate a mandatory amendment from approved plans. There's still some wonkiness around discarding right now, but that should be addressed by #760 
Relates to #756
=> Add amendment button for staff

src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/utils/helper/plan.js
Enables the discard button for staff after they create a mandatory amendment, and hides it when they submit it to the AH.
Relates to #760
=> Allow staff to discard mandatory amendments they initiate

src/components/common/Status.js, src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js, src/constants/api.js, src/styles/Common.scss
This PR styles the versions toolbar and contains some relevant information about the status us different versions. I have tried to make the current legal version stand out by colouring the avatar and the approved dot while greying out the other versions.
Does anyone have an RUP number that has multiple versions? I would like to take a look and see what the different statuses look like. As shown above, I could only find versions that had a status of approved.
=> Style versions toolbar

src/components/rangeUsePlanPage/pageForAH/AHSignatureModal.js, src/components/rangeUsePlanPage/pageForAH/index.js
The plan's amendment type wasn't being used when calling the `updateConfirmations` function from the signature modal. This caused the plan to go to a strange status when a minor amendment was signed by everybody, since it was behaving like an initial RUP.
Relates to #785
=> Send isMinorAmendment to confirmations endpoint

src/components/common/Status.js, src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js
In order to show the right start date for any Stands legal version, we need to (for now) hide the exact stage it's in (reviewed etc).  
- This change makes sure the status component gets passed user (from context) and that the status component only renders 'Stands' when that is applicable.  
- Fix legal end date pulling start date.
- Also some cleanup of unused content.
=> Show all stands as stands

src/components/rangeUsePlanPage/versionsList/VersionsDropdownList.js, src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js
- Aligned the Reason label when no reason is shown
- Evened out spacing between Reason, Legal Start and Legal End
=> Tidy up versions menu

src/api/plan.js
Frontend update to go along with https://github.com/bcgov/range-api/pull/215
=> Change capitalization of `iscurrentlegalversion` to camel case

src/api/plan.js, src/utils/helper/plan.js
Allows the user to amend from the past legal version when the current plan is a  not approved mandatory amendment, similar to the functionality with WMWE.
Relates to #822
=> Allow mandatory amendment to be amended from legal in Not Approved

src/components/rangeUsePlanPage/ActionBtns.js, src/components/rangeUsePlanPage/manageAgentsPage/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/components/router/index.js, src/constants/api.js, src/constants/routes.js
Adds a page, accessible by the 3-dot menu on the RUP page, to allow staff to manage agents for clients for a plan/agreement.
Relies on https://github.com/bcgov/range-api/pull/234.
Relates to #857
=> Create manage agents page

src/actionCreators/planActionCreator.js, src/api/plan.js, src/components/loginPage/SignInBox.js, src/components/rangeUsePlanPage/SubmitAsMandatoryButton.js, src/components/rangeUsePlanPage/basicInformation/index.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/notifications/AHSignaturesStatusModal.js, src/components/rangeUsePlanPage/pageForAH/AHSignatureModal.js, src/components/rangeUsePlanPage/pageForAH/AmendmentSubmissionModal.js, src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js, src/components/rangeUsePlanPage/pageForAH/confirmationTabs/AHConfirmationList.js, src/components/rangeUsePlanPage/pageForAH/confirmationTabs/ConfirmChoiceTab.js, src/components/rangeUsePlanPage/pageForAH/index.js, src/components/rangeUsePlanPage/pageForAH/submissionTabs/RequestSignaturesTab.js, src/components/rangeUsePlanPage/pageForAH/tabs/MandatoryTabsForMultipleAH.js, src/components/rangeUsePlanPage/pageForAH/tabs/MinorTabsForMultipleAH.js, src/components/rangeUsePlanPage/pageForAH/tabs/TabsForMultipleAH.js, src/components/rangeUsePlanPage/pageForStaff/index.js, src/components/rangeUsePlanPage/pdf/helper.js, src/components/rangeUsePlanPage/pdf/pdf/FrontPage.js, src/components/selectRangeUsePlanPage/PlanTableRow.js, src/components/selectRangeUsePlanPage/ZoneSelect.js, src/components/selectRangeUsePlanPage/index.js, src/providers/PlanProvider.js, src/utils/helper/client.js, src/utils/helper/plan.js
Whenever you sign/submit/create an amendment, all signatures that you are allowed to sign (ie. the AHs you are an agent for) will be updated accordingly. This means you can sign for all AHs you have agency for in one go.
Relates to #633
Depends on https://github.com/bcgov/range-api/pull/236
=> Allow agents to sign plans

src/components/rangeUsePlanPage/pageForStaff/index.js, src/components/selectRangeUsePlanPage/SortableAgreementTable.js, src/components/selectRangeUsePlanPage/ZoneSelect.js, src/utils/helper/plan.js
I've change the permissions so that range officers accessing plans outside of their assigned zone can not make any modifications to those plans.
I've also stored the selected zones the users if filtering by in the URL's query params, so the selection should stay across refreshes and when the user navigates back using browser history.
Relates to #563
=> Fix RUP permissions for plans outside zone

src/components/rangeUsePlanPage/ContentsContainer.js, src/components/rangeUsePlanPage/PlanForm.js, src/components/rangeUsePlanPage/attachments/AttachmentRow.js, src/components/rangeUsePlanPage/attachments/index.js, src/components/rangeUsePlanPage/pageForStaff/index.js
Fixes a couple of bugs with file attachments:
=> Fix attachments

src/components/manageClientPage/index.js
Sometimes, two or more users will use the same given name and email address which makes it difficult to diffrenciate the two users in the Manage Clients drop down. 
The dropdown now includes the username (or bceid) depending on which they use to log in.
=> Show username in Manage clients

src/components/rangeUsePlanPage/PlanForm.js
Fixes a bug where certain sections couldn't be scrolled to if a validation error was encountered, causing an error.
Relates to #896, #895
=> Add IDs to plan sections

src/components/rangeUsePlanPage/conditions/index.js, src/constants/permissions.js
Allow Range Officers and Decision Makers to edit their respective conditions fields in the correct statuses.
Relates to #855
=> Fix permissions for conditions fields

src/components/selectRangeUsePlanPage/ZoneSelect.js
This commit closes #318 
If user has a zone in the url the user does not have access to, the zone 
will be removed from url and agreements related will not be shown.
=> Restrict agreements if user not auth'd for zone in url

src/api/plan.js, src/api/user.js, src/components/assignRolesPage/index.js, src/components/common/PermissionsField.js, src/components/common/Status.js, src/components/common/Status.story.js, src/components/mainPage/Navbar.js, src/components/rangeUsePlanPage/PlanForm.js, src/components/rangeUsePlanPage/conditions/index.js, src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js, src/components/rangeUsePlanPage/index.js, src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js, src/components/router/index.js, src/components/selectRangeUsePlanPage/ZoneSelect.js, src/components/selectRangeUsePlanPage/index.js, src/constants/api.js, src/constants/permissions.js, src/constants/routes.js, src/constants/strings.js, src/constants/variables.js, src/providers/PlanProvider.js, src/utils/helper/plan.js, src/utils/helper/user.js
- Make role check consistent with new database change and setup navbar with new permissions
- Add missed files when merging
- Pair with api commit 1 to allow read only permission
- Change permission edit field to use new database role id
- WIP preparing for new assigning roles page, modules might be broken
- Add frontend for assign roles page and begin changes for how roles are read
- Clean a little bit for legacy roles stuff
- Fix plan page breaking with recent changes
- set error to null if error exists to avoid error persisting to other plans
- Remove draft option for non-admin in override options
=> DB Roles and Read only update

src/components/selectRangeUsePlanPage/SortableAgreementTable.js, src/components/selectRangeUsePlanPage/ZoneSelect.js, src/components/selectRangeUsePlanPage/index.js
- Edit which name column to sort by
- Save page number in localstorage and load it on startup
- Save page limit in localstorage aside the number
- Persist filter checkboxes on multiple page change
- Persist filters in localstorage
- Persist checkbox with extra initialize flag
- Persist zones for admin
- Persist zones for agrologist
- Store zones on handle close
=> Persist filters and checkboxes in localstorage
