bcgov/range-web

openshift/templates/caddy-bc.json
openshift/templates/caddy-dc.json

These are the openshift configuration template files for chained build.

adding caddy chained deployment config

---

src/components/selectRangeUsePlan/AgreementTable.js
src/constants/strings.js

the purpose of the pr is to
display a warning message for agreement holders when they don't have their client numbers

enhance/agreement-table -> dev

---

src/tests/intergration/ManageZone.test.js

forgot to mock GET /zone in integration testing

#2 enhance/manage-zone&client -> dev 

---

src/components/rangeUsePlan/BackBtn.js
src/components/selectRangeUsePlan/AgreementTable.js
src/components/selectRangeUsePlan/SearchBar.js
src/components/selectRangeUsePlan/SearchableAgreementTable.js
src/components/selectRangeUsePlan/index.js
src/styles/Normalize.scss
src/styles/pikaday.scss

notify users with a spinner in the agreement search bar when fetching agreements using the flag isFetchingAgreements from Redux store

enhance/select-rup-page -> enhance/styling-detail-rup-page

---

src/components/rangeUsePlan/BackBtn.js
src/components/rangeUsePlan/basicInformation/index.js
src/components/rangeUsePlan/pageForAH/ActionBtns.js
src/components/rangeUsePlan/pageForAH/index.js
src/components/rangeUsePlan/pageForStaff/index.js
src/components/rangeUsePlan/pdf/content/writeBasicInformation.js
src/components/selectRangeUsePlan/AgreementTable.js
src/components/selectRangeUsePlan/SearchBar.js
src/components/selectRangeUsePlan/SearchableAgreementTable.js
src/components/selectRangeUsePlan/index.js
src/styles/Normalize.scss
src/styles/Rup.scss
src/styles/pikaday.scss

Enhancing the styling for the detail RUP view.
The page can be found `/range-use-plan/:planId`

Enhance/styling detail rup page -> dev

---

src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js
src/components/rangeUsePlanPage/pageForStaff/UpdateStatusModal.js
src/components/rangeUsePlanPage/pageForStaff/UpdateZoneModal.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/components/rangeUsePlanPage/pageForStaff/props.js
src/constants/strings.js
src/styles/Rup.scss

enhance the behavior of the status dropdown
1. when clicked it fetches the plan before providing options to update the plan status
2. become disabled if there is no actions required

Enhance/plan actions -> dev

---

src/components/mainPage/index.js
src/components/manageClientPage/index.js
src/components/manageZonePage/index.js
src/components/rangeUsePlanPage/PDFViewFromServer.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pdf/PDFView.js
src/components/selectRangeUsePlanPage/index.js
src/constants/strings.js
src/reducers/authReducer.js
src/utils/authentication.js

handle network errors after reauthenticating in
1. manage client page
2. manage zone page
3. range use plan page
4. select range use plan page

Enhance/handle error when reauthenticate -> dev

---

src/actionCreators/commonActionCreator.js
src/components/manageClientPage/index.js
src/constants/api.js

fetch users with params in Manage Client page with the param the app will get users
1. ordered by client id in descending order
2. filtered by email with @gov.bc.ca a like

enhance/manage-client -> dev

---

src/components/rangeUsePlanPage/pdf/content/common.js
src/components/rangeUsePlanPage/pdf/content/writeGrazingSchedules.js
src/components/rangeUsePlanPage/pdf/content/writePlantCommunities/index.js

start a new page after each plant community, and don't add an extra one after before the schedules.

remove blank pages from pdf output

---

src/components/rangeUsePlanPage/pageForAH/tabs/TabsForMultipleAH.js

be more clear on wording about decision maker getting the final word.

change plan_status_submitted_for_review verbiage

---

.github/workflows/nodejs.yml

remove other node versions from test action

---

src/components/common/form/DateInputField.js
src/components/rangeUsePlanPage/managementConsiderations/ManagementConsiderationRow.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js
src/components/rangeUsePlanPage/schema.js

Fix more issues

---

.github/label-actions.yml

create label actions yaml after installing label actions app to repo

try label actions

---

src/components/rangeUsePlanPage/pastures/index.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js
src/components/rangeUsePlanPage/schema.js
src/constants/strings.js

Fixes the labels, default values and validation for some fields
Relates to #142, #139, #162, #151, #152, #136, #221

Adjust some fields 

---

src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/plantCommunities/index.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/index.js

Fixes a bug where user is unable to add a monitoring area to a plant community, and implements saving of new monitoring areas.
Related to #150, #179

Fix creation of monitoring areas

---

src/components/common/form/DayMonthPicker.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/schema.js

Allows the plant community action `details` field to be null. Also fixes a couple of eslint warnings/errors.
Resolves #249

Fix error with null values

---

src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js

In the indicator plants and plant community action dropdown, sets a custom value when the user blurs the field.
Relates to #169 and #177

Set value of dropdowns with addable options on blur

---

src/components/common/InputModal.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/pastures/index.js

Use dialog for pasture name

---

src/components/common/form/DayMonthPicker.js

Add default value for dateFormat in DayMonthPicker

---

src/components/rangeUsePlanPage/pdf/PDFView.js

Open PDFs in new tab on iOS

---

src/components/rangeUsePlanPage/basicInformation/index.js

simple help text renders based on plan end date vs agreement date, explains usage to range officers.

add help text for range officers about usage

---

src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js

Focus next field on enter in plant community actions and indicator plants

---

package-lock.json
package.json
src/api/index.js
src/components/common/PermissionsField.js
src/components/common/form/DateInputField.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.test.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.test.js
src/components/rangeUsePlanPage/grazingSchedules/PasturesDropdown.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/index.js
src/components/rangeUsePlanPage/grazingSchedules/index.test.js
src/components/rangeUsePlanPage/schema.js
src/setupTests.js
src/styles/Common.scss
src/tests/helpers/test-utils.js

Fixes the implementation of grazing schedules to more closely resemble what is currently in production, as well as resolving some of the bugs that were present there.
I've also added tests for the grazing schedule components. Hopefully this will provide a good stepping point for adding unit tests to more components in the app.
Relates to #291 and #292

Grazing Schedule fixes

---

src/components/common/form/OnSubmitValidationError.js

Fix validation error when form isn't touched

---

src/components/rangeUsePlanPage/PlanForm.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/utils/validation/plan.js

Most of the changes have to do with the refactor and adjusting it to integrate with the existing redux code. Hopefully will be stable enough until the submit portions of the app can be refactored as well.
Relates to #310, maybe #309

Fix errors when submitting

---

src/components/common/PermissionsField.js
src/components/rangeUsePlanPage/PlanForm.js
src/providers/EditableProvider.js
src/utils/helper/plan.js

Disable editing depending on status and user

---

src/components/rangeUsePlanPage/basicInformation/index.js

Fix display value for plan dates

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js

Fix elevation dropdown error

---

src/components/rangeUsePlanPage/ministerIssues/AddMinisterIssueActionButton.js
src/components/rangeUsePlanPage/ministerIssues/AddMinisterIssueButton.js
src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js

Relates to #340
Will fix also #337, #338

Populate "other" field when creating minister issue action

---

src/components/rangeUsePlanPage/schema.js

Make plant community description error nicer

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.test.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap

Include year in grazing schedule datepicker to fix crash

---

src/api/index.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.test.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/index.js
src/components/rangeUsePlanPage/grazingSchedules/index.test.js
src/components/rangeUsePlanPage/schema.js

Allow grazing schedules to be deleted

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js

Only allow schedules to be deleted if plan is editable

---

src/actionCreators/planActionCreator.js
src/utils/helper/amendment.js

Fixes the issues reported in #334.

Fix data errors on amendment submission

---

src/utils/helper/amendment.js

This should have been part of #364.

Add patch for missed grazing schedules error on amendment submission

---

src/components/rangeUsePlanPage/ActionBtns.js

Hide submit button if status is RFS

---

src/components/rangeUsePlanPage/managementConsiderations/index.js

Allow adding multiple management consideration of the same type in a row

---

src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js
src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js

Resolves issues #190, #191, and #170

Add placeholder text to minister issues and actions

---

src/components/common/form/HelpfulDropdown.js
src/components/common/form/HelpfulDropdown.story.js
src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js

Add help text to dropdowns that allow custom option

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js

I had to pull the placeholders form the minister issue action types ref.
Relates to #170

Add plant community action placeholders

---

src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/plantCommunities/AddPlantCommunityButton.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js

Adds placeholder text for:
* Additional requirements
* Pastures
* Plant communities
* Monitoring areas
Relates to #350

Add placeholders

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/index.js

Let range officers know plant communities are readonly after save

---

src/components/rangeUsePlanPage/plantCommunities/index.js

See https://github.com/bcgov/range-web/issues/383#issuecomment-563330596 for more details

Change plant community editable info message

---

src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js
src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js

Add required fields to Additional Requirements and Minister Issues

---

src/api/index.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/pastures/index.js
src/constants/api.js

Let pastures be deleted

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/index.js

The endpoint to update plant communities has been added, so we can reenable that functionality and remove the info message.

Make plant communities editable again

---

src/api/index.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/index.js
src/constants/api.js

Add button to delete plant communities

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js

Let plant community name be changed

---

src/api/index.js
src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js
src/components/rangeUsePlanPage/ministerIssues/index.js

Add button to delete minister issues

---

src/components/rangeUsePlanPage/plantCommunities/AddPlantCommunityButton.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js

Resolves a bug introduced in #395

Fix readonly display of plant community name

---

src/api/index.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/index.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/index.js
src/constants/api.js

Fix monitoring area delete and allow name to be edited

---

src/utils/calculation/grazingSchedule.js

try subtracting pld from calccrowntotalAUM

---

src/api/index.js
src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js
src/components/rangeUsePlanPage/additionalRequirements/index.js
src/constants/api.js

Let additional requirements be deleted

---

src/api/index.js
src/components/rangeUsePlanPage/pdf/helper.js

Adds 1 to the diffs.
Relates to #410

Fix schedule date difference calculation in PDFs

---

src/components/rangeUsePlanPage/basicInformation/index.js

fix hardcoded agreement type

---

src/actionCreators/index.js
src/actionCreators/schema.js
src/components/manageClientPage/ManageClientPage.js
src/utils/helper/manageZoneAndClient.js

Frontend updates that go along with https://github.com/bcgov/range-api/issues/90

Use client id instead of client number

---

src/components/common/MultiParagraphDisplay.js
src/components/common/PermissionsField.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js

Fix schedule description wrapping

---

src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js

Fix menus that don't allow the same option to be selected twice

---

src/api/delete.js
src/components/rangeUsePlanPage/plantCommunities/IndicatorPlant.js
src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js
src/components/rangeUsePlanPage/plantCommunities/criteria/RangeReadinessBox.js
src/components/rangeUsePlanPage/plantCommunities/criteria/StubbleHeightBox.js
src/constants/api.js

Make indicator plant deletes persistent

---

src/components/rangeUsePlanPage/schema.js

Add schema rule that plan end date must be after start

---

src/components/rangeUsePlanPage/schema.js

Make range name required field

---

src/components/rangeUsePlanPage/basicInformation/index.js

Mark basic informations fields as required

---

src/components/rangeUsePlanPage/invasivePlantChecklist/index.js

Disable invasive checklist if RUP is not editable

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap

Add schedule description description

---

src/components/rangeUsePlanPage/pdf/pdf/FrontPage.js

fix plan dates and text on front page

---

src/components/rangeUsePlanPage/PlanForm.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/constants/strings.js
src/utils/validation/pasture.js
src/utils/validation/plan.js

Validate pastures length before submission

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js

Default grace days to 0 in schedule row

---

src/components/rangeUsePlanPage/grazingSchedules/index.js

Update schedule years options when plan dates change

---

src/components/rangeUsePlanPage/pdf/pdf/Schedules.js

Add schedule description disclaimer to pdf

---

src/components/rangeUsePlanPage/grazingSchedules/index.js

Fix schedule component to pull from usage.

fix schedule usage

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
src/components/rangeUsePlanPage/grazingSchedules/PasturesDropdown.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap

Also fixes some styling bugs with the grazing schedule table.
Relates to #448

Populate schedule grace days when pasture is selected

---

src/components/rangeUsePlanPage/pastures/index.js

Exclude monitoring areas from pasture copy

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js

Set grace days to 0 if left blank

---

src/components/rangeUsePlanPage/pdf/helper.js

Show grace days in PDF from schedule row if set

---

src/components/rangeUsePlanPage/pdf/pdf/common/Table.js

Fix wrapping of pasture names with hyphens and underscores

---

src/components/rangeUsePlanPage/additionalRequirements/AdditionalRequirementRow.js
src/components/rangeUsePlanPage/additionalRequirements/index.js
src/utils/helper/additionalRequirement.js

Add copy option to additional requirements

---

src/utils/helper/plan.js

Allow agreement holder to edit in status 10

---

src/components/rangeUsePlanPage/BackBtn.js
src/components/rangeUsePlanPage/index.js
src/components/selectRangeUsePlanPage/AgreementTable.js
src/components/selectRangeUsePlanPage/PlanTable.js

Also fixes the back button behaviour.
Relates to #274

Prompt user before leaving page if there are unsaved changes

---

src/api/index.js
src/api/plan.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/components/rangeUsePlanPage/schema.js
src/utils/validation/grazingSchedule.js
src/utils/validation/plan.js

Change grazing schedule validation

---

src/components/rangeUsePlanPage/grazingSchedules/PasturesDropdown.js
src/components/rangeUsePlanPage/invasivePlantChecklist/index.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityBox.js

Fix clipping in readonly view for some fields

---

src/api/index.js
src/components/rangeUsePlanPage/grazingSchedules/index.js
src/utils/index.js

Keep order of parts of plan after saving

---

src/components/rangeUsePlanPage/pdf/pdf/Criteria.js

Add range readiness date and notes to PDF

---

src/components/common/SortableTableHeaderCell.js
src/components/rangeUsePlanPage/index.js

Replace history entry on RUP save

---

src/styles/Common.scss

Make collapsible boxes as tall as necessary

---

src/components/rangeUsePlanPage/pdf/pdf/Criteria.js
src/components/rangeUsePlanPage/pdf/pdf/PlantCommunity.js
src/constants/strings.js

Change plant community elevation unit to meters

---

src/components/rangeUsePlanPage/BackBtn.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/components/router/index.js
src/components/selectRangeUsePlanPage/PlanTableRow.js
src/components/selectRangeUsePlanPage/index.js

Fix back arrow behaviour

---

src/components/common/MultiParagraphDisplay.js
src/components/common/PermissionsField.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap
src/components/rangeUsePlanPage/pastures/PastureBox.js

Default to using MultiParagraphDisplay in PermissionsField

---

src/components/rangeUsePlanPage/index.js

Change prompt message when there are unsaved changes

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js

Remove other option from plant community action dropdown

---

src/components/rangeUsePlanPage/pdf/pdf/AdditionalRequirements.js
src/components/rangeUsePlanPage/pdf/pdf/BasicInformation.js
src/components/rangeUsePlanPage/pdf/pdf/Criteria.js
src/components/rangeUsePlanPage/pdf/pdf/Header.js
src/components/rangeUsePlanPage/pdf/pdf/InvasivePlants.js
src/components/rangeUsePlanPage/pdf/pdf/ManagementConsiderations.js
src/components/rangeUsePlanPage/pdf/pdf/MinisterIssues.js
src/components/rangeUsePlanPage/pdf/pdf/MonitoringArea.js
src/components/rangeUsePlanPage/pdf/pdf/Pastures.js
src/components/rangeUsePlanPage/pdf/pdf/PlantCommunity.js
src/components/rangeUsePlanPage/pdf/pdf/PlantCommunityActions.js
src/components/rangeUsePlanPage/pdf/pdf/Schedules.js
src/components/rangeUsePlanPage/pdf/pdf/common/ExplanatoryText.js
src/components/rangeUsePlanPage/pdf/pdf/common/config.js

Fix PDF display issues

---

src/components/rangeUsePlanPage/pdf/pdf/Criteria.js
src/components/rangeUsePlanPage/pdf/pdf/IndicatorPlants.js

[PDF] Use different label for stubble height values

---

src/components/rangeUsePlanPage/pdf/pdf/Pasture.js

Remove grace days from pasture in PDF

---

src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js

Make monitoring area location input bigger

---

src/providers/ToastProvider.js

Fix toast provide hooks usage

---

src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js
src/components/rangeUsePlanPage/pdf/pdf/MinisterIssueActions.js

No graze fix

---

src/components/rangeUsePlanPage/plantCommunities/PlantCommunityAction.js

Fix adding a value in community action dropdown

---

src/components/rangeUsePlanPage/ministerIssues/AddMinisterIssueActionButton.js

Stop minister issue action dropdown from keeping last selected value

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleEntryRow.js
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/GrazingScheduleEntryRow.test.js.snap
src/components/rangeUsePlanPage/grazingSchedules/__snapshots__/index.test.js.snap
src/components/rangeUsePlanPage/schema.js
src/providers/ToastProvider.js
src/styles/RupGrazingSchedule.scss

Shows an error if schedule date out is before date in.
Relates to #533

Validate schedule dates

---

src/components/rangeUsePlanPage/schema.js

Require whole number for allowable AUMs

---

src/components/common/form/DecimalField.js
src/components/rangeUsePlanPage/invasivePlantChecklist/index.js

Remove unnecessary leave page warnings

---

src/components/rangeUsePlanPage/index.js
src/providers/ToastProvider.js
src/styles/Toast.scss
src/utils/validation/plan.js

Add which field has an error if validation fails

---

src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js

add amount of AUM exceeded to  schedule error

---

src/components/rangeUsePlanPage/pdf/pdf/PlantCommunity.js

change plant community desc label  pdf

---

src/utils/helper/plan.js

get rid of iOS reference

---

src/components/rangeUsePlanPage/invasivePlantChecklist/index.js
src/components/rangeUsePlanPage/pdf/pdf/InvasivePlants.js

change text in  invasive checklist

---

src/components/rangeUsePlanPage/pdf/pdf/InvasivePlants.js
src/components/rangeUsePlanPage/pdf/pdf/PlantCommunity.js

PDF display fixes

---

src/components/rangeUsePlanPage/schema.js

Make monitoring area rangeland health not required

---

src/components/rangeUsePlanPage/plantCommunities/monitoringArea/MonitoringAreaBox.js

Sorry @LisaMoore1, forgot to include this change in #600
Relates to #599

Remove required indicator from rangeland health

---

src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js
src/styles/LoginPage.scss

Frontend PR to go along with https://github.com/bcgov/range-api/pull/134
Biggest change is all version creation responsibility has been moved to API.

Minor versioning changes

---

src/api/plan.js
src/components/App.js
src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/DiscardAmendmentButton.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pageForAH/AmendmentSubmissionModal.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/constants/api.js
src/constants/strings.js
src/providers/PlanProvider.js
src/utils/helper/plan.js

* When AH submits a minor amendment now, it goes into "Stands - Review". Staff can then review the amendment and mark it as "Stands" as "Stands - Wrongly made".
* Allows minor amendments to be discarded by restoring the latest legal version of a snapshot (right now, approved and stands plans).
Relates to #606

Complete minor amendment workflow

---

src/components/rangeUsePlanPage/plantCommunities/monitoringArea/index.js

Clear id when copying monitoring area

---

src/utils/helper/plantCommunity.js

Clear createdAt field on monitoring area copy

---

src/components/rangeUsePlanPage/pdf/pdf/InvasivePlants.js

[PDF] Remove "other" prefix in invasive plants

---

src/components/rangeUsePlanPage/schema.js

force integers for pld

---

package-lock.json
src/components/mainPage/Navbar.js
src/components/rangeUsePlanPage/pastures/PastureBox.js

hide manage zones, leave it  in the  file  for devs

---

src/components/rangeUsePlanPage/pdf/pdf/common/Table.js

add few special chars to regex for wrapping

---

src/components/rangeUsePlanPage/schema.js

force integers for grace  days

---

src/components/mainPage/Navbar.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pastures/PastureBox.js
src/providers/PlanProvider.js

Hard refetch plan when page change to clear out stale data

---

src/components/rangeUsePlanPage/pastures/index.js

Set index to null when closing copy pasture dialog

---

src/components/rangeUsePlanPage/ActionBtns.js

Change sign submission menu item into button

---

src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js

Adds the date and status of the version.
Also refactored the dropdown to use material-ui.
Relates to #662

Add more info to version dropdown

---

src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pageForAH/index.js

Add loading indicator when creating amendment

---

src/components/rangeUsePlanPage/versionsList/VersionsList.js

filter irrelevant versions for the user

only show approved versions in version list

---

src/components/rangeUsePlanPage/ActionBtns.js

Relates to https://github.com/bcgov/range-api/issues/163

Temporarily remove create amendment button

---

.eslintrc.js
src/components/rangeUsePlanPage/index.js

Refetch plan when "Retry" button is pressed on error page

---

src/actionCreators/index.js
src/components/rangeUsePlanPage/pageForAH/AHSignatureModal.js
src/components/rangeUsePlanPage/pageForAH/SubmissionModal.js
src/components/rangeUsePlanPage/pdf/helper.js
src/components/selectRangeUsePlanPage/AHWarning.js
src/constants/api.js
src/tests/intergration/mockData/mockUsers.js
src/utils/helper/client.js
src/utils/helper/manageZoneAndClient.js
src/utils/helper/plan.js

Fix signing 

---

src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js

- Cleaned up the layout of the version toolbar. 
- Approved chip is disabled if not the current agreement

Show legal versions

---

src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js

show legal start and end date in version list

---

src/components/rangeUsePlanPage/pdf/pdf/MonitoringArea.js

Add check in case rangeland health is null

---

package-lock.json
package.json
src/components/rangeUsePlanPage/additionalRequirements/index.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js
src/components/rangeUsePlanPage/grazingSchedules/index.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/managementConsiderations/index.js
src/components/rangeUsePlanPage/ministerIssues/MinisterIssueBox.js
src/components/rangeUsePlanPage/ministerIssues/index.js
src/components/rangeUsePlanPage/pastures/index.js
src/components/rangeUsePlanPage/plantCommunities/IndicatorPlantsForm.js
src/components/rangeUsePlanPage/plantCommunities/PlantCommunityActionsBox.js
src/components/rangeUsePlanPage/plantCommunities/index.js
src/components/rangeUsePlanPage/plantCommunities/monitoringArea/index.js

Remove any validation that was happening before on field change, field blur, or field array changes. Validation should only run before submit now.
Relates to #653

Validate only on save

---

src/components/manageClientPage/ClientLinkList.js
src/tests/intergration/ManageClientPage.test.js
src/tests/intergration/mockData/mockUsers.js

Hide client link error after selecting a different client

---

src/components/rangeUsePlanPage/pageForStaff/index.js

Add loading indicator for staff amendment creation

---

src/components/rangeUsePlanPage/ministerIssues/MinisterIssueAction.js

make minister issue action detail required

---

src/api/plan.js

Related API PR: https://github.com/bcgov/range-api/pull/197

Use new discard endpoint for discard button

---

src/constants/api.js

My bad, forget to commit this along with #779

Add missing api constant

---

src/utils/helper/plan.js

Make plan editable when submitted as mandatory

---

src/api/plan.js
src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/AmendFromLegalButton.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/utils/helper/plan.js

Add button to amend when plan is wrongly made without effect

---

src/api/plan.js
src/components/rangeUsePlanPage/pageForAH/AmendmentSubmissionModal.js

Update confirmation when submitting minor amendment

---

src/components/rangeUsePlanPage/versionsList/VersionsToolbar.js

fyi @okanji i had to update the component to use that camelcase var and also incorporate `legal_reason`, since the endpoint is already updated and deployed i had to get this out prior to your changes, hopefully that doesn't cause you too much grief.

update versions toolbar to use new attributes from endpoint

---

src/components/common/Status.js
src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/components/selectRangeUsePlanPage/PlanTableRow.js
src/styles/Common.scss
src/styles/Rup.scss

I've added a little amendment label to the status component. I've also fixed the spacing of the action buttons when they wrap.
Relates to #755 and #782

Add amendment label to the status component

---

src/components/rangeUsePlanPage/index.js

Only refetch plan if pathname changes

---

public/index.html

as per https://gist.github.com/kirillshevch/a7d778a6aaa788149ae86a9b313cb0ad#gistcomment-2917775
first crack at #537

Try to disable caching

---

src/components/common/form/PercentField.js
src/components/rangeUsePlanPage/schema.js

fix javascript math weirdness causing pld issues for only some numbers

---

src/components/common/Status.js

https://github.com/bcgov/range-web/pull/807#issuecomment-631679704

make sure status component is passed isForVersionsList prop

---

src/components/rangeUsePlanPage/versionsList/VersionsDropdownList.js

This is in response to https://github.com/bcgov/range-web/issues/700#issuecomment-631717673

Made legal version green colour and added reason column 

---

src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js

Save plan before submission

---

src/index.js

Temporarily unregister service worker

---

src/api/user.js
src/components/manageClientPage/ClientDropdown.js
src/components/manageClientPage/ClientLinkList.js
src/tests/intergration/ManageClientPage.test.js
src/tests/intergration/mockData/mockClients.js

Relies on https://github.com/bcgov/range-api/pull/229

Change manage client page to link/unlink all location codes

---

src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js

Run form validation before submitting

---

src/components/selectRangeUsePlanPage/ZoneSelect.js

Should hopefully fix the error found by @micheal-w-wells: https://github.com/bcgov/range-web/issues/537#issuecomment-654269897

Handle users with no name in zone select

---

src/components/selectRangeUsePlanPage/SortableAgreementTable.js

Hide new plan button for other zones

---

src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pageForAH/confirmationTabs/AHConfirmationList.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/constants/permissions.js
src/constants/variables.js
src/utils/helper/plan.js
src/utils/helper/user.js

Switches some permissions around so the DM will make the final decision instead of ROs.
Relates to #855

Move decision buttons to decision maker

---

src/components/rangeUsePlanPage/pageForStaff/index.js

Validate and save before updating status

---

src/components/rangeUsePlanPage/managementConsiderations/ManagementConsiderationRow.js
src/components/rangeUsePlanPage/schema.js

Make management consideration details required

---

src/components/rangeUsePlanPage/pdf/pdf/AdditionalRequirements.js
src/components/rangeUsePlanPage/pdf/pdf/ManagementConsiderations.js
src/components/rangeUsePlanPage/pdf/pdf/PlantCommunity.js

Make URLs in PDF actual links

---

src/components/rangeUsePlanPage/manageAgentsPage/index.js

Changes to the agent linking page implemented based on the suggestions in https://github.com/bcgov/range-web/issues/857#issuecomment-662682308: 
- Add success message when agents are saved
- Make clear button always visible if an agent is selected
- Add a back button
- Add RAN to header
Relates to #857

Agency linking page changes

---

src/components/rangeUsePlanPage/manageAgentsPage/index.js

Relates to https://github.com/bcgov/range-web/issues/857#issuecomment-663100216

Change agents page back button appearance

---

src/components/rangeUsePlanPage/pageForStaff/index.js

Relates to https://github.com/bcgov/range-web/issues/378#issuecomment-662609175

Validate minister toggles on update status

---

src/components/rangeUsePlanPage/pdf/pdf/FrontPage.js

Change PDF agent signature wording

---

src/components/rangeUsePlanPage/PlanForm.js
src/components/rangeUsePlanPage/conditions/index.js
src/constants/fields.js
src/constants/permissions.js
src/constants/strings.js
src/constants/variables.js
src/utils/helper/plan.js

Created section for conditions for the decision maker to edit.

created conditions section

---

src/components/rangeUsePlanPage/ContentsContainer.js
src/components/rangeUsePlanPage/grazingSchedules/GrazingScheduleBox.js

Reset sort order on duplicate or add

---

src/constants/strings.js
src/utils/validation/ministerIssue.js
src/utils/validation/plan.js

Validate minister issues identified toggle

---

src/components/selectRangeUsePlanPage/SortableAgreementTable.js

Adds a sortable district column to the agreement table.
Relates to #847

Add district column to agreement table

---

src/components/rangeUsePlanPage/PlanForm.js
src/utils/helper/plan.js

Change when attachments are allowed to be added

---

src/api/plan.js
src/components/rangeUsePlanPage/index.js
src/components/rangeUsePlanPage/pageForAH/index.js
src/components/rangeUsePlanPage/pageForStaff/index.js
src/components/rangeUsePlanPage/pdf/PDFView.js
src/providers/PlanProvider.js

Don't attempt to save attachments if no permission

---

src/utils/validation/ministerIssue.js

Fix minister issue toggle validation

---

src/components/rangeUsePlanPage/pageForStaff/index.js
src/utils/helper/plan.js

Allow Range Officers to save draft in SFD

---

src/components/rangeUsePlanPage/attachments/index.js
src/styles/RupAttachments.scss

Add labels for attachment categories

---

src/components/rangeUsePlanPage/conditions/index.js
src/utils/helper/plan.js

* Changes the recommend conditions field label to "Staff Recommended Conditions"
* Disallow DM from entering conditions in status MSR (minor amendment - stands, in review)
Relates to #911, #912

Conditions changes

---

src/api/user.js

change payload for client link to say client id and not number

---

src/components/rangeUsePlanPage/ActionBtns.js
src/components/rangeUsePlanPage/pageForStaff/UpdateStatusDropdown.js
src/components/rangeUsePlanPage/pageForStaff/index.js

Restrict override plan actions to just admin

---

src/components/selectRangeUsePlanPage/SortableAgreementTable.js
src/components/selectRangeUsePlanPage/index.js

- Switch over from status like filter to multi select
- Persist status code filters when changing pages

status filters

---

src/api/user.js
src/components/assignRolesAndDistrictsPage/index.js
src/components/selectRangeUsePlanPage/index.js
src/constants/strings.js
src/utils/helper/user.js

- [rebase] Display default values to assign roles and districts on user select
- [rebase] Allow saving of both user role and districts at the same time and refresh role displayed
- Make edits for many to many relationship change for districts and users
- Remove zone select for read only

Merge roles and districts and allow multiple district assigning
